services:
  frontend:
    image: cfrontend:${IMAGE_TAG}
    container_name: frontend
    # environment:
    #   - REACT_APP_API_URL=http://backend:8888
    ports:
      - "80:80"
    expose:
      - 80
    depends_on:
      - backend
    # volumes:
    #   - /home/vagrant/API_URL:/usr/share/nginx/html
    
  backend:
    image: cbackend:${IMAGE_TAG}
    container_name: backend
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=inventory
      - DB_PORT=5432
    ports:
      - "8888:8888"
    expose:
      - 8888
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: cpostgresql:${IMAGE_TAG}
    container_name: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


